# Generated by Django 3.2.18 on 2024-12-02 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcondition',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PatientCondition', to='DataBase.reservation'),
        ),
    ]
