# Generated by Django 3.2.18 on 2024-12-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0002_alter_patientcondition_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientcondition',
            old_name='Service',
            new_name='Reservation',
        ),
    ]
